Description: The vpc/network related ressources
Parameters:
  ProjectName:
    Type: String
  VPCCIDR:
    Type: String
  SubPublicVPCCIDR1:
    Type: String
  SubPublicVPCCIDR2:
    Type: String
  SubPrivateVPCCIDR1:
    Type: String
  SubPrivateVPCCIDR2:
    Type: String

Resources:
  VPC:
    Type: AWS::EC2::VPC
    Properties:
      CidrBlock: !Ref VPCCIDR
      EnableDnsHostnames: true
      Tags:
        - Key: Name
          Value: !Ref ProjectName

  InternetGateway:
    Type: AWS::EC2::InternetGateway
    Properties:
      Tags:
      - Key: Name
        Value: !Sub Internet Gateway for ${ProjectName}

  InternetGatewayAttachment:
    Type: AWS::EC2::VPCGatewayAttachment
    Properties:
      InternetGatewayId: !Ref InternetGateway
      VpcId: !Ref VPC

  PublicSubnetOne:
    Type: AWS::EC2::Subnet
    Properties:
      AvailabilityZone: !Select [0, !GetAZs '']
      VpcId: !Ref VPC
      CidrBlock: !Ref SubPublicVPCCIDR1
      MapPublicIpOnLaunch: true
      Tags:
        - Key: Name
          Value: !Sub subnet ${ProjectName} Public Subnet {AZ1}

  PublicSubnetTwo:
    Type: AWS::EC2::Subnet
    Properties:
      AvailabilityZone: !Select [1, !GetAZs '']
      VpcId: !Ref VPC
      CidrBlock: !Ref SubPublicVPCCIDR2
      MapPublicIpOnLaunch: true
      Tags:
        - Key: Name
          Value: !Sub subnet ${ProjectName} Public Subnet {AZ2}

  PrivateSubnetOne:
    Type: AWS::EC2::Subnet
    Properties:
      AvailabilityZone: !Select [0, !GetAZs '']
      VpcId: !Ref VPC
      CidrBlock: !Ref SubPrivateVPCCIDR1
      MapPublicIpOnLaunch: false
      Tags:
        - Key: Name
          Value: !Sub subnet ${ProjectName} Private Subnet {AZ1}

  PrivateSubnetTwo:
    Type: AWS::EC2::Subnet
    Properties:
      AvailabilityZone: !Select [1, !GetAZs '']
      VpcId: !Ref VPC
      CidrBlock: !Ref SubPrivateVPCCIDR2
      MapPublicIpOnLaunch: false
      Tags:
        - Key: Name
          Value: !Sub subnet ${ProjectName} Private Subnet {AZ2}

  NatGateway1EIP:
    Type: AWS::EC2::EIP
    DependsOn: InternetGatewayAttachment
    Properties: 
      Domain: vpc
      Tags: 
        - Key : Name
          Value: !Sub EIP Public Subnet 1 ${ProjectName} {AZ1}

  NatGatewayPublicSubnet1:
    Type: AWS::EC2::NatGateway
    Properties: 
      AllocationId: !GetAtt NatGateway1EIP.AllocationId
      SubnetId: !Ref  PublicSubnetOne
      Tags: 
        - Key : Name
          Value: !Sub Gateway Public Subnet 1 ${ProjectName} {AZ1}

  NatGateway2EIP:
    Type: AWS::EC2::EIP
    DependsOn: InternetGatewayAttachment
    Properties: 
      Domain: vpc
      Tags: 
        - Key : Name
          Value: !Sub EIP Public Subnet 2 ${ProjectName} {AZ2}

  NatGatewayPublicSubnet2:
    Type: AWS::EC2::NatGateway
    Properties: 
      AllocationId: !GetAtt NatGateway2EIP.AllocationId
      SubnetId: !Ref  PublicSubnetTwo
      Tags: 
        - Key : Name
          Value: !Sub Gateway Public Subnet 2 ${ProjectName} {AZ2}

  PublicRouteTable:
    Type: AWS::EC2::RouteTable
    Properties: 
      Tags: 
        - Key: Name
          Value: !Sub ${ProjectName} Public Route Table
      VpcId: !Ref VPC

  DefaultPublicRoute: 
        Type: AWS::EC2::Route
        DependsOn: InternetGatewayAttachment
        Properties: 
            RouteTableId: !Ref PublicRouteTable
            DestinationCidrBlock: 0.0.0.0/0
            GatewayId: !Ref InternetGateway

  PublicSubnetRoutAssociation1:
    Type: AWS::EC2::SubnetRouteTableAssociation
    Properties: 
      RouteTableId: !Ref PublicRouteTable
      SubnetId: !Ref PublicSubnetOne

  PublicSubnetRoutAssociation2:
    Type: AWS::EC2::SubnetRouteTableAssociation
    Properties: 
      RouteTableId: !Ref PublicRouteTable
      SubnetId: !Ref PublicSubnetTwo



  PrivateRouteTable1:
    Type: AWS::EC2::RouteTable
    Properties: 
      Tags: 
        - Key: Name
          Value: !Sub ${ProjectName} Public Route Table {AZ1}
      VpcId: !Ref VPC

  PrivateRoute1: 
        Type: AWS::EC2::Route
        DependsOn: InternetGatewayAttachment
        Properties: 
            RouteTableId: !Ref PrivateRouteTable1
            DestinationCidrBlock: 0.0.0.0/0
            NatGatewayId: !Ref NatGatewayPublicSubnet1

  PrivateSubnetRoutAssociation1:
    Type: AWS::EC2::SubnetRouteTableAssociation
    Properties: 
      RouteTableId: !Ref PrivateRouteTable1
      SubnetId: !Ref PrivateSubnetOne


  PrivateRouteTable2:
    Type: AWS::EC2::RouteTable
    Properties: 
      Tags: 
        - Key: Name
          Value: !Sub ${ProjectName} Public Route Table {AZ2}
      VpcId: !Ref VPC

  PrivateRoute2: 
        Type: AWS::EC2::Route
        DependsOn: InternetGatewayAttachment
        Properties: 
            RouteTableId: !Ref PrivateRouteTable2
            DestinationCidrBlock: 0.0.0.0/0
            NatGatewayId: !Ref NatGatewayPublicSubnet2

  PrivateSubnetRoutAssociation2:
    Type: AWS::EC2::SubnetRouteTableAssociation
    Properties: 
      RouteTableId: !Ref PrivateRouteTable2
      SubnetId: !Ref PrivateSubnetTwo

      
Outputs:
  VPCID:
    Description: Public VPC reference
    Value: !Ref VPC
    Export:
      Name: !Sub ${ProjectName}-VPCID

  PublicSubnet:
    Description: Public Subnet reference
    Value: !Join [",", [!Ref PublicSubnetOne,!Ref PublicSubnetTwo]]
    Export:
      Name: !Sub ${ProjectName}-PUB-SUBNETS

  PrivateSubnet:
    Description: Private Subnet reference
    Value: !Join [",", [!Ref PrivateSubnetOne,!Ref PrivateSubnetTwo]]
    Export:
      Name: !Sub ${ProjectName}-PRIV-SUBNETS
      
      
      
      
      
      
      
      
      
      
      
      
      